package us.ttyl.chance.domain;



/**
 * TBodytype generated by MyEclipse - Hibernate Tools
 */

public class TBodytype  implements java.io.Serializable {


    // Fields    

     private Integer bodytypeId;
     private String bodytypeDesc;


    // Constructors

    /** default constructor */
    public TBodytype() {
    }

    
    /** full constructor */
    public TBodytype(String bodytypeDesc) {
        this.bodytypeDesc = bodytypeDesc;
    }

   
    // Property accessors

    public Integer getBodytypeId() {
        return this.bodytypeId;
    }
    
    public void setBodytypeId(Integer bodytypeId) {
        this.bodytypeId = bodytypeId;
    }

    public String getBodytypeDesc() {
        return this.bodytypeDesc;
    }
    
    public void setBodytypeDesc(String bodytypeDesc) {
        this.bodytypeDesc = bodytypeDesc;
    }
   








}