package us.ttyl.chance.domain;



/**
 * TColor generated by MyEclipse - Hibernate Tools
 */

public class TColor  implements java.io.Serializable {


    // Fields    

     private Integer colorId;
     private String colorDesc;


    // Constructors

    /** default constructor */
    public TColor() {
    }

    
    /** full constructor */
    public TColor(String colorDesc) {
        this.colorDesc = colorDesc;
    }

   
    // Property accessors

    public Integer getColorId() {
        return this.colorId;
    }
    
    public void setColorId(Integer colorId) {
        this.colorId = colorId;
    }

    public String getColorDesc() {
        return this.colorDesc;
    }
    
    public void setColorDesc(String colorDesc) {
        this.colorDesc = colorDesc;
    }
   








}