package us.ttyl.chance.domain;



/**
 * TEthnicity generated by MyEclipse - Hibernate Tools
 */

public class TEthnicity  implements java.io.Serializable {


    // Fields    

     private Integer ethnicityId;
     private String ethnicityDesc;


    // Constructors

    /** default constructor */
    public TEthnicity() {
    }

    
    /** full constructor */
    public TEthnicity(String ethnicityDesc) {
        this.ethnicityDesc = ethnicityDesc;
    }

   
    // Property accessors

    public Integer getEthnicityId() {
        return this.ethnicityId;
    }
    
    public void setEthnicityId(Integer ethnicityId) {
        this.ethnicityId = ethnicityId;
    }

    public String getEthnicityDesc() {
        return this.ethnicityDesc;
    }
    
    public void setEthnicityDesc(String ethnicityDesc) {
        this.ethnicityDesc = ethnicityDesc;
    }
   








}