package us.ttyl.chance.domain;



/**
 * THasChildren generated by MyEclipse - Hibernate Tools
 */

public class THasChildren  implements java.io.Serializable {


    // Fields    

     private Integer hasChildrenId;
     private String hasChildrenDesc;


    // Constructors

    /** default constructor */
    public THasChildren() {
    }

    
    /** full constructor */
    public THasChildren(String hasChildrenDesc) {
        this.hasChildrenDesc = hasChildrenDesc;
    }

   
    // Property accessors

    public Integer getHasChildrenId() {
        return this.hasChildrenId;
    }
    
    public void setHasChildrenId(Integer hasChildrenId) {
        this.hasChildrenId = hasChildrenId;
    }

    public String getHasChildrenDesc() {
        return this.hasChildrenDesc;
    }
    
    public void setHasChildrenDesc(String hasChildrenDesc) {
        this.hasChildrenDesc = hasChildrenDesc;
    }
   








}