package us.ttyl.chance.domain;



/**
 * TIdealBodytype generated by MyEclipse - Hibernate Tools
 */

public class TIdealBodytype  implements java.io.Serializable {


    // Fields    

     private TIdealBodytypeId id;


    // Constructors

    /** default constructor */
    public TIdealBodytype() {
    }

    

   
    // Property accessors

    public TIdealBodytypeId getId() {
        return this.id;
    }
    
    public void setId(TIdealBodytypeId id) {
        this.id = id;
    }
   








}