package us.ttyl.chance.domain;



/**
 * TLookingfor generated by MyEclipse - Hibernate Tools
 */

public class TLookingfor  implements java.io.Serializable {


    // Fields    

     private Integer lookingforId;
     private String lookingforDesc;


    // Constructors

    /** default constructor */
    public TLookingfor() {
    }

    
    /** full constructor */
    public TLookingfor(String lookingforDesc) {
        this.lookingforDesc = lookingforDesc;
    }

   
    // Property accessors

    public Integer getLookingforId() {
        return this.lookingforId;
    }
    
    public void setLookingforId(Integer lookingforId) {
        this.lookingforId = lookingforId;
    }

    public String getLookingforDesc() {
        return this.lookingforDesc;
    }
    
    public void setLookingforDesc(String lookingforDesc) {
        this.lookingforDesc = lookingforDesc;
    }
   








}