package us.ttyl.chance.domain;



/**
 * TPicture generated by MyEclipse - Hibernate Tools
 */

public class TPicture  implements java.io.Serializable {


    // Fields    

     private Integer pictureId;
     private User user;
     private String filenamePath;
     private Integer mainPagePic;
     private Integer deleted;

    // Constructors

    /** default constructor */
    public TPicture() {
    }

    
    /** full constructor */
    public TPicture(String filenamePath, User user, Integer mainPagePic, Integer deleted) 
    {
        this.filenamePath = filenamePath;
        this.user = user;
        this.mainPagePic = mainPagePic;
        this.deleted = deleted;
    }

   
    // Property accessors

    public Integer getPictureId() {
        return this.pictureId;
    }
    
    public void setPictureId(Integer pictureId) {
        this.pictureId = pictureId;
    }

    public String getFilenamePath() {
        return this.filenamePath;
    }
    
    public void setFilenamePath(String filenamePath) {
        this.filenamePath = filenamePath;
    }


	public User getUser() {
		return user;
	}


	public void setUser(User user) {
		this.user = user;
	}


	public Integer getMainPagePic() {
		return mainPagePic;
	}


	public void setMainPagePic(Integer mainPagePic) {
		this.mainPagePic = mainPagePic;
	}


	public Integer getDeleted() {
		return deleted;
	}


	public void setDeleted(Integer deleted) {
		this.deleted = deleted;
	}
	
	
}