package us.ttyl.chance.domain;



/**
 * TState generated by MyEclipse - Hibernate Tools
 */

public class TState  implements java.io.Serializable {


    // Fields    

     private Integer stateId;
     private Integer countryId;
     private String stateCode;
     private String stateDesc;


    // Constructors

    /** default constructor */
    public TState() {
    }

    
    /** full constructor */
    public TState(Integer countryId, String stateCode, String stateDesc) {
        this.countryId = countryId;
        this.stateCode = stateCode;
        this.stateDesc = stateDesc;
    }

   
    // Property accessors

    public Integer getStateId() {
        return this.stateId;
    }
    
    public void setStateId(Integer stateId) {
        this.stateId = stateId;
    }

    public Integer getCountryId() {
        return this.countryId;
    }
    
    public void setCountryId(Integer countryId) {
        this.countryId = countryId;
    }

    public String getStateCode() {
        return this.stateCode;
    }
    
    public void setStateCode(String stateCode) {
        this.stateCode = stateCode;
    }

    public String getStateDesc() {
        return this.stateDesc;
    }
    
    public void setStateDesc(String stateDesc) {
        this.stateDesc = stateDesc;
    }
   








}