package us.ttyl.chance.domain;



/**
 * TUserPictureId generated by MyEclipse - Hibernate Tools
 */

public class TUserPictureId  implements java.io.Serializable {


    // Fields    

     private Integer userId;
     private Integer pictureId;


    // Constructors

    /** default constructor */
    public TUserPictureId() {
    }

    
    /** full constructor */
    public TUserPictureId(Integer userId, Integer pictureId) {
        this.userId = userId;
        this.pictureId = pictureId;
    }

   
    // Property accessors

    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    public Integer getPictureId() {
        return this.pictureId;
    }
    
    public void setPictureId(Integer pictureId) {
        this.pictureId = pictureId;
    }
   



   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TUserPictureId) ) return false;
		 TUserPictureId castOther = ( TUserPictureId ) other; 
         
		 return ( (this.getUserId()==castOther.getUserId()) || ( this.getUserId()!=null && castOther.getUserId()!=null && this.getUserId().equals(castOther.getUserId()) ) )
 && ( (this.getPictureId()==castOther.getPictureId()) || ( this.getPictureId()!=null && castOther.getPictureId()!=null && this.getPictureId().equals(castOther.getPictureId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getUserId() == null ? 0 : this.getUserId().hashCode() );
         result = 37 * result + ( getPictureId() == null ? 0 : this.getPictureId().hashCode() );
         return result;
   }   





}