package us.ttyl.chance.domain;



/**
 * TUserIdealLookingfor generated by MyEclipse - Hibernate Tools
 */

public class TUserIdealLookingfor  implements java.io.Serializable {


    // Fields    

     private TUserIdealLookingforId id;


    // Constructors

    /** default constructor */
    public TUserIdealLookingfor() {
    }

    

   
    // Property accessors

    public TUserIdealLookingforId getId() {
        return this.id;
    }
    
    public void setId(TUserIdealLookingforId id) {
        this.id = id;
    }
   








}