package us.ttyl.chance.domain;

import java.util.Date;


/**
 * TUsermessages generated by MyEclipse - Hibernate Tools
 */

public class TUsermessages  implements java.io.Serializable {


    // Fields    

     private Integer messageId;
     private User userIdFrom;
     private User userIdTo;
     private String messageSubject;
     private String messageContent;
     private Date createdOn;
     private Date deletedOn;
     private Byte deleted;
     private Date viewedOn;

    // Constructors

    /** default constructor */
    public TUsermessages() {
    }

    
    /** full constructor */
    public TUsermessages(User userIdFrom, User userIdTo, String messageSubject, String messageContent, Date createdOn, Date deletedOn, Byte deleted, Date viewedOn) 
    {
        this.userIdFrom = userIdFrom;
        this.userIdTo = userIdTo;
        this.messageSubject = messageSubject;
        this.messageContent = messageContent;
        this.createdOn = createdOn;
        this.deletedOn = deletedOn;
        this.deleted = deleted;
        this.viewedOn = viewedOn;
    }
   
   // Property accessors
    public Integer getMessageId() {
        return this.messageId;
    }
    
    public void setMessageId(Integer messageId) {
        this.messageId = messageId;
    }

    public User getUserIdFrom() {
        return this.userIdFrom;
    }
    
    public void setUserIdFrom(User userIdFrom) {
        this.userIdFrom = userIdFrom;
    }

    public User getUserIdTo() {
        return this.userIdTo;
    }
    
    public void setUserIdTo(User userIdTo) {
        this.userIdTo = userIdTo;
    }

    public String getMessageSubject() {
        return this.messageSubject;
    }
    
    public void setMessageSubject(String messageSubject) {
        this.messageSubject = messageSubject;
    }

    public String getMessageContent() {
        return this.messageContent;
    }
    
    public void setMessageContent(String messageContent) {
        this.messageContent = messageContent;
    }

	public Date getCreatedOn() {
		return createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	public byte getDeleted() {
		return deleted;
	}

	public void setDeleted(byte deleted) {
		this.deleted = deleted;
	}

	public Date getDeletedOn() {
		return deletedOn;
	}

	public void setDeletedOn(Date deletedOn) {
		this.deletedOn = deletedOn;
	}


	public Date getViewedOn() {
		return viewedOn;
	}


	public void setViewedOn(Date viewedOn) {
		this.viewedOn = viewedOn;
	}
}