package us.ttyl.chance.domain;



/**
 * TUserIdealEthnicity generated by MyEclipse - Hibernate Tools
 */

public class TUserIdealEthnicity  implements java.io.Serializable {


    // Fields    

     private TUserIdealEthnicityId id;


    // Constructors

    /** default constructor */
    public TUserIdealEthnicity() {
    }

    

   
    // Property accessors

    public TUserIdealEthnicityId getId() {
        return this.id;
    }
    
    public void setId(TUserIdealEthnicityId id) {
        this.id = id;
    }
   








}