package us.ttyl.chance.domain;



/**
 * TUserIdealEthnicityId generated by MyEclipse - Hibernate Tools
 */

public class TUserIdealEthnicityId  implements java.io.Serializable {


    // Fields    
	 private Integer id; 
     private Integer userId;
     private Integer idealEthnicityId;


    // Constructors

    /** default constructor */
    public TUserIdealEthnicityId() {
    }

    
    /** full constructor */
    public TUserIdealEthnicityId(Integer userId, Integer idealEthnicityId) {
        this.userId = userId;
        this.idealEthnicityId = idealEthnicityId;
    }

   
    // Property accessors

    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    public Integer getIdealEthnicityId() {
        return this.idealEthnicityId;
    }
    
    public void setIdealEthnicityId(Integer idealEthnicityId) {
        this.idealEthnicityId = idealEthnicityId;
    }
   



   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TUserIdealEthnicityId) ) return false;
		 TUserIdealEthnicityId castOther = ( TUserIdealEthnicityId ) other; 
         
		 return ( (this.getUserId()==castOther.getUserId()) || ( this.getUserId()!=null && castOther.getUserId()!=null && this.getUserId().equals(castOther.getUserId()) ) )
 && ( (this.getIdealEthnicityId()==castOther.getIdealEthnicityId()) || ( this.getIdealEthnicityId()!=null && castOther.getIdealEthnicityId()!=null && this.getIdealEthnicityId().equals(castOther.getIdealEthnicityId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getUserId() == null ? 0 : this.getUserId().hashCode() );
         result = 37 * result + ( getIdealEthnicityId() == null ? 0 : this.getIdealEthnicityId().hashCode() );
         return result;
   }


public Integer getId() {
	return id;
}


public void setId(Integer id) {
	this.id = id;
}   





}