package us.ttyl.chance.domain;



/**
 * TUserIdealLookingforId generated by MyEclipse - Hibernate Tools
 */

public class TUserIdealLookingforId  implements java.io.Serializable {


    // Fields    

     private Integer userId;
     private Integer idealLookingforId;
     private Integer id;


    // Constructors

    public Integer getId() {
		return id;
	}


	public void setId(Integer id) {
		this.id = id;
	}


	/** default constructor */
    public TUserIdealLookingforId() {
    }

    
    /** full constructor */
    public TUserIdealLookingforId(Integer userId, Integer idealLookingforId) {
        this.userId = userId;
        this.idealLookingforId = idealLookingforId;
    }

   
    // Property accessors

    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    public Integer getIdealLookingforId() {
        return this.idealLookingforId;
    }
    
    public void setIdealLookingforId(Integer idealLookingforId) {
        this.idealLookingforId = idealLookingforId;
    }
   



   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TUserIdealLookingforId) ) return false;
		 TUserIdealLookingforId castOther = ( TUserIdealLookingforId ) other; 
         
		 return ( (this.getUserId()==castOther.getUserId()) || ( this.getUserId()!=null && castOther.getUserId()!=null && this.getUserId().equals(castOther.getUserId()) ) )
 && ( (this.getIdealLookingforId()==castOther.getIdealLookingforId()) || ( this.getIdealLookingforId()!=null && castOther.getIdealLookingforId()!=null && this.getIdealLookingforId().equals(castOther.getIdealLookingforId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getUserId() == null ? 0 : this.getUserId().hashCode() );
         result = 37 * result + ( getIdealLookingforId() == null ? 0 : this.getIdealLookingforId().hashCode() );
         return result;
   }   





}