package us.ttyl.chance.domain;



/**
 * TWantsChildren generated by MyEclipse - Hibernate Tools
 */

public class TWantsChildren  implements java.io.Serializable {


    // Fields    

     private Integer wantsChildrenId;
     private String wantsChildrenDesc;


    // Constructors

    /** default constructor */
    public TWantsChildren() {
    }

    
    /** full constructor */
    public TWantsChildren(String wantsChildrenDesc) {
        this.wantsChildrenDesc = wantsChildrenDesc;
    }

   
    // Property accessors

    public Integer getWantsChildrenId() {
        return this.wantsChildrenId;
    }
    
    public void setWantsChildrenId(Integer wantsChildrenId) {
        this.wantsChildrenId = wantsChildrenId;
    }

    public String getWantsChildrenDesc() {
        return this.wantsChildrenDesc;
    }
    
    public void setWantsChildrenDesc(String wantsChildrenDesc) {
        this.wantsChildrenDesc = wantsChildrenDesc;
    }
   








}